{{- if .Values.vault_settings.hashicorp_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: database-host
      objectName: database-host
    - key: database-db
      objectName: database-db
    - key: user
      objectName: user
    - key: password
      objectName: password
    secretName: {{ .Values.secrets.deps_high_sparrow.secretName }}
    type: Opaque
  parameters:
    roleName: "{{ .Values.csi.roleName }}"
    vaultAddress: "https://vault_host"
    vaultNamespace: "vault_namespace"
    vaultSkipTLSVerify: "true"
    #vaultCACertPath: ""
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    objects: |
      - objectName: "message-broker-driver"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-driver"
      - objectName: "message-broker-connection-string"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-connection-string"
      - objectName: "database-host"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "database-host"
      - objectName: "database-db"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-high-sparrow/high-sparrow-database"
        secretKey: "database-db"
      - objectName: "user"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-high-sparrow/high-sparrow-database"
        secretKey: "user"
      - objectName: "password"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-high-sparrow/high-sparrow-database"
        secretKey: "password"
{{- end }}
