{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "high-sparrow-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "high-sparrow-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "high-sparrow-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "new-validation-process"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_high_sparrow.secretName }}
      type: Opaque
      data:
        - objectName: "high-sparrow-db-user"
          key: user
        - objectName: "high-sparrow-db-password"
          key: password
        - objectName: "db-host"
          key: database-host
        - objectName: "high-sparrow-db"
          key: database-db
        - objectName: "new-validation-process"
          key: new-validation-process
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
{{- end }}
