{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-database-host/versions/latest" 
        fileName: "database-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-high-sparrow-db-user/versions/latest" 
        fileName: "user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-high-sparrow-db-password/versions/latest" 
        fileName: "password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-high-sparrow-db/versions/latest" 
        fileName: "database-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/new-validation-process/versions/latest" 
        fileName: "new-validation-process"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_high_sparrow.secretName }}
      type: Opaque
      data:
      - objectName: "new-validation-process"
        key: new-validation-process
      - objectName: "database-host"
        key: database-host
      - objectName: "user"
        key: user
      - objectName: "password"
        key: password
      - objectName: "database-db"
        key: database-db
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
{{- end }}
