version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./etc/high-sparrow/Dockerfile
      target: develop
      args:
        REPOSITORY_URL: "${REPOSITORY_URL}"
      cache_from:
        - "high-sparrow-dev:latest"
    env_file:
      - ./etc/high-sparrow/env/.dev.env
      - .env
    networks:
      - deps-network
    volumes:
      - ./src/deps_high_sparrow:/app/deps_high_sparrow
      - ./src/tests:/app/tests
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./vendors:/vendors
      - ./src/setup.cfg:/app/setup.cfg
    ports:
      - "8052:8000"
    stdin_open: true
    tty: true

  consumer:
    build:
      context: .
      dockerfile: ./etc/high-sparrow/Dockerfile
      target: develop
      args:
        REPOSITORY_URL: "${REPOSITORY_URL}"
      cache_from:
        - "high-sparrow-dev:latest"
    env_file:
      - ./etc/high-sparrow/env/.dev.env
      - .env
    networks:
      - deps-network
    volumes:
      - ./src/deps_high_sparrow:/app/deps_high_sparrow
      - ./src/tests:/app/tests
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./vendors:/vendors
    stdin_open: true
    tty: true

  migrator:
    build:
      context: .
      dockerfile: ./etc/migrator/Dockerfile
      args:
        REPOSITORY_URL: "${REPOSITORY_URL}"
      cache_from:
        - "high-sparrow-migrator:latest"
    env_file: ./etc/migrator/env/.dev.env
    networks:
      - deps-network
    volumes:
      - ./etc/migrator/migrations:/app/migrations

networks:
  deps-network:
    external: true
