{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Values.secrets.deps_high_sparrow_migrator.secretName }}
    type: Opaque
    data:
      - key: high-sparrow-db-password
        objectName: high-sparrow-db-password
      - key: high-sparrow-db
        objectName: high-sparrow-db
      - key: high-sparrow-db-user
        objectName: high-sparrow-db-user
      - key: db-host
        objectName: db-host 
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }} 
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}  
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }} 
    objects: |
      array:
        - |
          objectName: "high-sparrow-db-password"
          objectType: secret

        - |
          objectName: "high-sparrow-db"
          objectType: secret

        - |
          objectName: "high-sparrow-db-user"
          objectType: secret

        - |
          objectName: "db-host"
          objectType: secret

{{- end }}
